### ISSUE TITLE
There are missing days from JHU Dataset 

### ISSUE THREAD

**Issue by DreamITSoftware** [cipriancraciun/covid19-datasets#30] opened 2020-04-08 16:34 UTC

**Comment by cipriancraciun** [comment] 2020-04-08 18:25
@DreamITSoftware could you be more specific?

Are these days missing only from my derived files, or they are missing also from the original JHU dataset?

**Comment by cipriancraciun** [comment] 2020-04-09 11:01
@DreamITSoftware I've manually checked the input files for each date and they seem to be all there.

Therefore I'm closing this ticket for now without any action.

If you can detail more about this issue, please re-open it.

**Closed as completed by cipriancraciun** 2020-04-09 11:01 UTC
Labels: datasets, fixup

**Comment by DreamITSoftware** [comment] 2020-04-15 14:12
I pulled the tsv file and brought it into Excel.  I filtered by country United States and Province blank.  I sorted by date.  The dates are 1/22, 1/24, 1/26, 1/31 with additional dates missing in between.  There is an 8 day gap between 2/13 and 2/21 with missing info.  This set here https://github.com/cipriancraciun/covid19-datasets/tree/master/exports/jhu/v1/daily

**Comment by cipriancraciun** [comment] 2020-04-15 16:46
Yes, you are right there are missing dates, however the explanation is because in between those dates no actual data was changed (for either of the `confirmed`, `deaths` or `recovered` columns and the derived ones).

Basically I decided to drop the lines that don't provide any new data, mainly because they are due to bad reporting.

Thus not having them is a clear marker for the scientists that we have missing data and they can decide what to do:  just copy the previous value, interpolate, or treat it as missing data.
